### Practice solving triangular matrices

Here is a 3x3 set of linear equations that can be solved using forward substitution.

$$ 2x_1  = 1 $$
$$  3x_1 -7x_2 = -2 $$
$$ x_1 + 3x_2 - x_3 = 8 $$

First, put the equations into Ax=b form:

In [151]:
x = zeros(3)

# Fill A and b:
A = [2 0 0; 3 -7 0; 1 3 -1];
b = [1; -2; 8];

In [152]:
# Now, the system of equations can be solved using this forward substitution algorithm:

x[1]=b[1]/A[1,1]
x[2]=(b[2]-A[2,1]*x[1])/A[2,2]
x[3]=(b[3]-A[3,1]*x[1]-A[3,2]*x[2])/A[3,3]

@show x[1]
@show x[2]
@show x[3]

x[1] = 0.5
x[2] = 0.5
x[3] = -6.0


-6.0

In [153]:
# Fill A and b:
A = [2 0 0; 3 -7 0; 1 3 -1];
b = [1; -2; 8];

n = size(A, 1)
x = zeros(n)
x[1] = b[1]/A[1,1]

0.5

### Forward substitution to solve an lower-triangular linear system

In [154]:
"""
forwardsub(L,b)

Solve the lower-triangular linear system with matrix `L` and
right-hand side vector `b`.
"""
function forwardsub(L,b)

n = size(L,1)
x = zeros(n)
x[1] = b[1]/L[1,1]
    
for i = 2:n
    for j=1:i-1
        s = sum( L[i,j]*x[j])
            
        x[i] = ( b[i] - s ) / L[i,i]
            
    end 
end

return x
end

forwardsub

In [155]:
forwardsub(A, b)

3-element Vector{Float64}:
  0.5
  0.5
 -6.5

In [156]:
"""
forwardsub(L,b)

Solve the lower-triangular linear system with matrix `L` and
right-hand side vector `b`.
"""
function forwardsub1(L,b)

n = size(L,1)
x = zeros(n)
x[1] = b[1]/L[1,1]
for i = 2:n
    s = sum( L[i,j]*x[j] for j=1:i-1 )
    x[i] = ( b[i] - s ) / L[i,i]
end

return x
end

forwardsub1

In [157]:
forwardsub1(A, b)

3-element Vector{Float64}:
  0.5
  0.5
 -6.0

### Backward substitution to solve an upper-triangular linear system

In [144]:
"""
backsub(U,b)

Solve the upper-triangular linear system with matrix `U` and
right-hand side vector `b`.
"""
function backsub(U,b)

n = size(U,1)
x = zeros(n)
x[n] = b[n]/U[n,n]
for i = n-1:-1:1
    s = sum( U[i,j]*x[j] for j=i+1:n )
    x[i] = ( b[i] - s ) / U[i,i]
end

return x
end

backsub

In [145]:
U = [3 2 1; 0 1 -1; 0 0 2];
b = [1; 2; -4];


backsub(U, b)

3-element Vector{Float64}:
  1.0
  0.0
 -2.0